// This file is generated by Sapper — do not edit it!
export const timestamp = 1556305504259;

export const files = [
	"/service-worker-index.html",
	"favicon.png",
	"global.css",
	"great-success.png",
	"manifest.json",
	"svelte-logo-192.png",
	"svelte-logo-512.png"
];
export { files as assets }; // legacy

export const shell = [
	"client/chunk.3ba4eeed.js",
	"client/client.cb9bcb9f.js",
	"client/chunk.7973cc52.js",
	"client/chunk.679b8f4d.js",
	"client/chunk.7994a8e7.js",
	"client/chunk.e8d1afb8.js",
	"client/chunk.66640646.js"
];

export const routes = [
	{ pattern: /^\/?$/ },
	{ pattern: /^\/about\/?$/ },
	{ pattern: /^\/blog\/?$/ },
	{ pattern: /^\/blog\/([^\/]+?)\/?$/ }
];